# Generated by Django 4.2.4 on 2023-09-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
