# Generated by Django 4.2.5 on 2023-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_code',
            name='ORM_query',
            field=models.TextField(blank=True, max_length='30000', null=True),
        ),
        migrations.AlterField(
            model_name='query_code',
            name='SQL_query',
            field=models.TextField(blank=True, max_length='30000', null=True),
        ),
    ]
